import { useEffect, useState } from "react";
import { Bell, CheckCircle } from "lucide-react";
import { Badge } from "../components/ui/Badge";
import { PageHeader } from "../components/ui/PageHeader";
import { Panel } from "../components/ui/Panel";

const API = "/api/v1";

interface Alert {
  id: string;
  type: string;
  severity: string;
  title: string;
  message: string;
  acknowledged: boolean;
  createdAt: string;
  account?: {
    accountRef: string;
    riskStatus: string;
  }
}

const severityTone = (sev: string) => {
  if (sev === "CRITICAL") return "danger";
  if (sev === "HIGH") return "warning";
  return "intel";
};

export function AlertsPage() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchAlerts();
  }, []);

  const fetchAlerts = async () => {
    setLoading(true);
    const res = await fetch(`${API}/alerts`);
    const data = await res.json();
    setAlerts(data);
    setLoading(false);
  };

  const acknowledge = async (id: string) => {
    await fetch(`${API}/alerts/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ acknowledged: true })
    });
    fetchAlerts();
  };

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Notifications"
        title="Alerts"
        description="Internal notifications generated by the risk engine, such as activity on watched accounts."
      />

      <Panel>
        {loading ? (
          <p className="text-sm text-ink-500">Loading...</p>
        ) : alerts.length === 0 ? (
          <div className="text-center py-12 border border-dashed border-ink-200 dark:border-ink-800 rounded">
            <Bell className="h-10 w-10 mx-auto text-ink-300 dark:text-ink-600 mb-3" />
            <p className="text-sm text-ink-500">No alerts found.</p>
          </div>
        ) : (
          <div className="space-y-4">
            {alerts.map(a => (
              <div 
                key={a.id} 
                className={`flex items-start justify-between p-4 rounded-lg border ${
                  a.acknowledged 
                    ? 'border-ink-200 dark:border-ink-800 bg-transparent opacity-60' 
                    : 'border-intel/30 bg-intel/5 dark:bg-intel/10'
                }`}
              >
                <div className="flex gap-4">
                  <div className="mt-1">
                    <Badge tone={severityTone(a.severity)}>{a.severity}</Badge>
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <h4 className={`font-semibold text-sm ${a.acknowledged ? 'text-ink-500' : 'text-ink-900 dark:text-ink-100'}`}>
                        {a.title}
                      </h4>
                      {a.account && (
                        <span className="font-mono text-xs text-ink-500">({a.account.accountRef})</span>
                      )}
                      <span className="text-xs text-ink-400">• {new Date(a.createdAt).toLocaleString()}</span>
                    </div>
                    <p className={`text-sm ${a.acknowledged ? 'text-ink-400' : 'text-ink-600 dark:text-ink-300'}`}>
                      {a.message}
                    </p>
                  </div>
                </div>
                
                {!a.acknowledged && (
                  <button 
                    onClick={() => acknowledge(a.id)}
                    className="flex items-center gap-1 text-xs font-medium text-ink-500 hover:text-intel p-2 rounded hover:bg-intel/10 transition-colors"
                  >
                    <CheckCircle className="h-4 w-4" /> Acknowledge
                  </button>
                )}
              </div>
            ))}
          </div>
        )}
      </Panel>
    </div>
  );
}
